/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cde550dd-4313-4e5d-82ed-bcd001dc9361",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TMehXsZZF",
    "aws_user_pools_web_client_id": "2k35fdht39hqocu6i8bss5huu1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "eventful-events-images223524-staging",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "search_indices": {
                "items": [
                    "eventfulPlaces-staging"
                ],
                "default": "eventfulPlaces-staging"
            },
            "maps": {
                "items": {
                    "EvenfulMaps-staging": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "EvenfulMaps-staging"
            }
        }
    }
};


export default awsmobile;
